server:
  port: 7005
spring:
  application:
    name: order
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1:8000/eureka
    instance-id: ${spring.application.name}:${sever.port}   
