server:
  port: 7001

spring:
  application:
    name: user
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1:8000/eureka
    instance-id: ${spring.application.name}:${sever.port}
